### ISSUE TITLE
How to use metricq JS？

### ISSUE THREAD

**Issue by hl0709** [metricq/metricq-js#4]
Excuse me, how to use metricq JS? I put it under the directory of grafana / data / plugins. It doesn't work. Do you have any specific steps?

**Comment by kinnarr** [comment]
`metricq-js` is a JavaScript library to connect to MetricQ from your own js code. For a Grafana datasource plugin have a look at [metricq/grafana-metricq-datasource](https://github.com/metricq/grafana-metricq-datasource).

To see how to use the `metricq-js` library, you can look at the examples `history_example.{html,js}` and `live_example.{html,js}`.

**Comment by tilsche** [comment]
We understand that the current documentation surrounding MetricQ is sparse at best. Let us know if you need any further support in setting it up - best with a specific use case.
